FROM eclipse-temurin:23
RUN mkdir /examples
WORKDIR /examples
COPY effects effects
COPY gradle gradle
COPY src src
COPY docker docker
COPY *.kts ./
COPY *.properties ./
RUN sed -i '/alias(libs.plugins.gitSemVer)/d' build.gradle.kts
COPY gradlew* ./
RUN ./gradlew tasks
