FROM python:3.13.2
RUN mkdir /examples
WORKDIR /examples
COPY .python-version ./
COPY plotter/diameterPlotter.py ./
COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD python plotter/subnetDiameterPlotter.py
